# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=150)),
                ('email', models.TextField(verbose_name=50)),
                ('contraseña', models.TextField(verbose_name=50)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
