# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.TextField(max_length=50),
        ),
    ]
