# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_auto_20160410_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
